function t121_setHeight(recid){var rec=$('#rec'+recid);var div=$("#youtubeiframe"+recid);var height=div.width()*0.5625;div.height(height);div.parent().height(height);var videoLazy=rec.find('.t-video-lazyload');var iframeLazy=videoLazy.find('iframe');if(videoLazy!=undefined){var heightLazy=videoLazy.width()*0.5625;videoLazy.height(heightLazy);iframeLazy.height(heightLazy)}}
function t282_showMenu(recid){var el=$("#rec"+recid);el.find('.t282__burger, .t282__menu__item:not(".tooltipstered"):not(".t282__menu__item_submenu"), .t282__overlay').click(function(){if($(this).is(".t282__menu__item.tooltipstered, .t794__tm-link")){return}
$('body').toggleClass('t282_opened');el.find('.t282__menu__container, .t282__overlay').toggleClass('t282__closed');el.find(".t282__menu__container").css({'top':(el.find(".t282__container").height()+'px')})});$('.t282').bind('clickedAnchorInTooltipMenu',function(){$('body').removeClass('t282_opened');$('#rec'+recid+' .t282__menu__container, #rec'+recid+' .t282__overlay').addClass('t282__closed')})}
function t282_changeSize(recid){var el=$("#rec"+recid);var bottomheight=el.find(".t282__menu__container");var headerheight=el.find(".t282__container");var menu=bottomheight.height()+headerheight.height();var win=$(window).height();if(menu>win){$("#nav"+recid).addClass('t282__menu_static')}
else{$("#nav"+recid).removeClass('t282__menu_static')}}
function t282_changeBgOpacityMenu(recid){var window_width=$(window).width();var record=$("#rec"+recid);record.find(".t282__container__bg").each(function(){var el=$(this);var bgcolor=el.attr("data-bgcolor-rgba");var bgcolor_afterscroll=el.attr("data-bgcolor-rgba-afterscroll");var bgopacity=el.attr("data-bgopacity");var bgopacity_afterscroll=el.attr("data-bgopacity2");var menu_shadow=el.attr("data-menu-shadow");if($(window).scrollTop()>20){el.css("background-color",bgcolor_afterscroll);if(bgopacity_afterscroll!="0"&&bgopacity_afterscroll!="0.0"){el.css('box-shadow',menu_shadow)}else{el.css('box-shadow','none')}}else{el.css("background-color",bgcolor);if(bgopacity!="0"&&bgopacity!="0.0"){el.css('box-shadow',menu_shadow)}else{el.css('box-shadow','none')}}})}
function t282_highlight(recid){var url=window.location.href;var pathname=window.location.pathname;if(url.substr(url.length-1)=="/"){url=url.slice(0,-1)}
if(pathname.substr(pathname.length-1)=="/"){pathname=pathname.slice(0,-1)}
if(pathname.charAt(0)=="/"){pathname=pathname.slice(1)}
if(pathname==""){pathname="/"}
$(".t282__menu a[href='"+url+"']").addClass("t-active");$(".t282__menu a[href='"+url+"/']").addClass("t-active");$(".t282__menu a[href='"+pathname+"']").addClass("t-active");$(".t282__menu a[href='/"+pathname+"']").addClass("t-active");$(".t282__menu a[href='"+pathname+"/']").addClass("t-active");$(".t282__menu a[href='/"+pathname+"/']").addClass("t-active")}
function t282_appearMenu(recid){var window_width=$(window).width();$(".t282").each(function(){var el=$(this);var appearoffset=el.attr("data-appearoffset");if(appearoffset!=""){if(appearoffset.indexOf('vh')>-1){appearoffset=Math.floor((window.innerHeight*(parseInt(appearoffset)/100)))}
appearoffset=parseInt(appearoffset,10);if($(window).scrollTop()>=appearoffset){if(el.css('visibility')=='hidden'){el.finish();el.css("top","-50px");el.css("visibility","visible");el.animate({"opacity":"1","top":"0px"},200,function(){})}}else{el.stop();el.css("visibility","hidden")}}})}
function t389_scrollToTop(){$('html, body').animate({scrollTop:0},700)}
function t675_init(recid){var el=$("#rec"+recid),textwrapper=el.find('.t675__textwrapper'),dots=el.find('.t-slds__bullet_wrapper');textwrapper.css('margin-bottom',dots.outerHeight()+7)}